// <auto-generated />
namespace Blog.Data.CodeFirst.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FirstBlogEntry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstBlogEntry));
        
        string IMigrationMetadata.Id
        {
            get { return "201303282022132_FirstBlogEntry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
