// <auto-generated />
using System;
using Blog.Data.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Data.Migrations.Migrations;

[DbContext(typeof(BlogDbContext))]
partial class BlogDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Blog.Data.EFCore.BlogEntryEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Entry")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("PostedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.ToTable("BlogEntries", (string)null);
            });

        modelBuilder.Entity("Blog.Data.EFCore.BlogEntryTagEntity", b =>
            {
                b.Property<int>("BlogEntryId")
                    .HasColumnType("int");

                b.Property<int>("TagId")
                    .HasColumnType("int");

                b.HasKey("BlogEntryId", "TagId");

                b.HasIndex("TagId");

                b.ToTable("BlogEntryTags", (string)null);
            });

        modelBuilder.Entity("Blog.Data.EFCore.TagEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("LookupID")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.ToTable("Tags", (string)null);
            });

        modelBuilder.Entity("Blog.Data.EFCore.BlogEntryTagEntity", b =>
            {
                b.HasOne("Blog.Data.EFCore.BlogEntryEntity", "BlogEntry")
                    .WithMany("BlogEntryTags")
                    .HasForeignKey("BlogEntryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Blog.Data.EFCore.TagEntity", "Tag")
                    .WithMany("BlogEntryTags")
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("BlogEntry");

                b.Navigation("Tag");
            });

        modelBuilder.Entity("Blog.Data.EFCore.BlogEntryEntity", b =>
            {
                b.Navigation("BlogEntryTags");
            });

        modelBuilder.Entity("Blog.Data.EFCore.TagEntity", b =>
            {
                b.Navigation("BlogEntryTags");
            });
#pragma warning restore 612, 618
    }
}
